---
# tasks file for sshdssm
  - name: Install SSM agent
    yum:
      name: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm"
      state: present
      disable_gpg_check: yes

  - name: Enable amazon-ssm-agent service
    service:
      name: amazon-ssm-agent
      enabled: yes

  - name: Copy sshd config file Script to remote machine
    copy:
      src: templates/sshd_config.sh
      dest: /home/cloudxmigration/
      owner: cloudxmigration
      #group: ec2-user
      mode: '0755'

  - name: Run the script to update sshd config
    become: true
    command: sh /home/cloudxmigration/sshd_config.sh

  - name: remove any possible duplicate sshd binary and configs
    file:
      path: "{{ item }}"
      state: absent
    with_items: 
      - /usr/local/sbin/sshd
      - /usr/local/etc/sshd_config
      - /usr/local/etc/ssh_config
      - /usr/local/bin/ssh

  - name: Restart service sshd
    service:
      name: sshd
      state: restarted
