---
# tasks file for step one

- name: fetch server version
  win_shell: (Get-WmiObject -class Win32_OperatingSystem).Caption
  register: serverver

#- debug:
#    var: serverver

- name: change netlogon parameters to 1 if windows 2012 R2 
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters\
    name: "{{ item }}"
    data: 1
    type: dword
  with_items:
    - RequireSignOrSeal
    - SealSecureChannel
    - SignSecureChannel
  ignore_errors: true
  when: serverver.stdout | search("Microsoft Windows Server 2012 R2")

- name: Remove netlogon parameter refusepasswordchange if windows 2012 R2
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters\
    name: refusepasswordchange
    state: absent
    type: dword
  ignore_errors: true
  when: serverver.stdout | search("Microsoft Windows Server 2012 R2")

#- name: Rebooting the server
#  win_reboot:
#  when: repo_code1.changed or repo_code2.changed

