---
# tasks file for ansible-prewig/roles/winec2config

- name: Stop EC2 Config Service
  win_service:
    name: Ec2Config
    state: stopped 
  ignore_errors: yes


- name: Uninstall EC2Config if present
  win_shell: |
    $remove = Get-ChildItem -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall, HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall |
    Get-ItemProperty |
        Where-Object {$_.DisplayName -match "EC2config" } |
            Select-Object -Property DisplayName, UninstallString
    ForEach ($ver in $remove) {
       If ($ver.UninstallString) {
           echo $ver.UninstallString
           $uninst = $ver.UninstallString
           echo $uninst
           & cmd /c $uninst /quiet /norestart
       }
    }
  ignore_errors: true


#  win_command: Ec2Install.exe /uninstall /quiet
#  args:
#    chdir: C:\post_migration

- name: Clear Ec2Config old data
  win_file:
    path: "{{ item }}"
    state: absent
  with_items:
    - 'C:\Program Files\Amazon\Ec2ConfigService'
    - 'C:\Programdata\Amazon\Ec2ConfigService'
  ignore_errors: yes




- name: Re-install EC2Config Service
  win_command: Ec2Install.exe /quiet
  args:
    chdir: C:\post_migration
